apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflows-ci-app-of-apps
spec:
  project: default
  source:
    repoURL: https://gogs.local/Workflows-CI.git
    targetRevision: HEAD
    path: argo/applications
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
